server:
  port: 8080
spring:
  # jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/face_class?useUnide=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true
    username: root
    password: root
    hikari:
      # 最小连接数
      minimum-idle: 1
      # 最大连接数
      maximum-pool-size: 20
      # 自动提交
      auto-commit: true
      # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      idle-timeout: 10000
      # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 30000
      # 连接测试查询语句
      connection-test-query: SELECT 1
  redis:
    database: 0
    password:
    port: 6379
    host: localhost
    lettuce:
      pool:
        min-idle: 5
        max-idle: 10
        max-active: 8
        max-wait: 1ms
      shutdown-timeout: 100ms
#Mybatis配置
mybatis:
  # mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  # pojo类所在包路径
  type-aliases-package: com.sofot1851.swl.face.entity
  configuration:
    map-underscore-to-camel-case: true
